/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminImportsRouteImport } from './routes/_authenticated/admin.imports'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminTranslationsRouteImport } from './routes/_authenticated/admin.translations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportsRoute =
  AuthenticatedAdminImportsRouteImport.update({
    id: '/imports',
    path: '/imports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTranslationsRoute =
  AuthenticatedAdminTranslationsRouteImport.update({
    id: '/translations',
    path: '/translations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/translations': typeof AuthenticatedAdminTranslationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/translations': typeof AuthenticatedAdminTranslationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/translations': typeof AuthenticatedAdminTranslationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/imports'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/imports'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/imports'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/translations'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imports': {
      id: '/_authenticated/admin/imports'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AuthenticatedAdminImportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/translations': {
      id: '/_authenticated/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AuthenticatedAdminTranslationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminImportsRoute: typeof AuthenticatedAdminImportsRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTranslationsRoute: typeof AuthenticatedAdminTranslationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminImportsRoute: AuthenticatedAdminImportsRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTranslationsRoute: AuthenticatedAdminTranslationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
